services:
  db:
    container_name: megalo_db
    hostname: postgresserver
    image: postgres:14
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  adminer:
    container_name: megalo_adminer
    hostname: adminer
    image: adminer:4.7.5
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db

volumes:
  dbdata: 
    name: megalo
