services:
  db:
    container_name: megalo_db
    hostname: postgresserver
    image: postgres:14
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
volumes:
  dbdata: 
    name: megalo
